services:
  mysql:
    image: mysql:8.0
    container_name: integration-testing-mysql
    ports:
      - "4000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 15s
      retries: 5
      start_period: 30s
      timeout: 10s
